/// TypeScript + JavaScript test runner.
///
/// Strategy: assemble the user's solution and the lesson's tests into
/// a single Node-runnable script under `<scratch>/run.mjs`, then
/// invoke Node with `--experimental-strip-types` (Node 22.6+) so we
/// can run `.ts` files without a separate transpile step. For older
/// Nodes we fall back to a `tsx`-style on-the-fly transpile via
/// `--import @swc-node/register` IF the package is installed in the
/// extension's bundled `node_modules` — which it isn't by default,
/// so users on Node < 22.6 currently get a clean "please upgrade
/// Node" error.
///
/// The expected lesson shape mirrors the desktop app's tests
/// pipeline: the user's `solution.ts` exports the functions under
/// test; the hidden `tests.ts` does `import { foo } from
/// './solution'` and uses a tiny assert helper from the assembled
/// runtime. We inject a minimal `assert` stub into the assembled
/// run.mjs so courses don't need to depend on a test framework.
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { readMaybe, resetScratch, spawnCapture, which } from "./util";
import type { RunInput, RunResult, Runner } from "./types";

const TS_RUNTIME_HEADER = `// Auto-generated by the Libre VSCode extension. Do not edit.
// Provides the minimal assertion + test helpers the lesson's tests
// expect, so the lesson author doesn't have to ship vitest/mocha.
let __passed = 0;
let __failed = 0;
const __failures = [];

globalThis.test = (name, fn) => {
  try {
    const r = fn();
    if (r && typeof r.then === 'function') {
      return r.then(
        () => { __passed++; console.log('  ok ' + name); },
        (e) => { __failed++; __failures.push({ name, err: e }); console.log('  FAIL ' + name); }
      );
    }
    __passed++;
    console.log('  ok ' + name);
  } catch (e) {
    __failed++;
    __failures.push({ name, err: e });
    console.log('  FAIL ' + name);
  }
};
globalThis.expect = (got) => ({
  toBe: (want) => {
    if (!Object.is(got, want)) throw new Error('expected ' + JSON.stringify(want) + ', got ' + JSON.stringify(got));
  },
  toEqual: (want) => {
    if (JSON.stringify(got) !== JSON.stringify(want)) throw new Error('expected ' + JSON.stringify(want) + ', got ' + JSON.stringify(got));
  },
  toThrow: () => {
    let threw = false;
    try { got(); } catch { threw = true; }
    if (!threw) throw new Error('expected function to throw');
  },
});
globalThis.assert = (cond, msg) => {
  if (!cond) throw new Error(msg ?? 'assertion failed');
};

const __reportSummary = () => {
  console.log('\\n' + __passed + ' passed, ' + __failed + ' failed.');
  for (const { name, err } of __failures) {
    console.log('\\n  ✗ ' + name);
    console.log('    ' + (err && err.message ? err.message : String(err)));
  }
  process.exitCode = __failed === 0 ? 0 : 1;
};
process.on('beforeExit', __reportSummary);
`;

export const typescriptRunner: Runner = {
  displayName: "TypeScript / JavaScript (node --experimental-strip-types)",
  languages: ["typescript", "javascript"],
  async run(input: RunInput): Promise<RunResult> {
    const node = await which("node");
    if (!node) {
      return {
        status: "error",
        output:
          "`node` not found on PATH. Install Node.js 22.6+ from https://nodejs.org and reload the VSCode window.",
        summary: "Node toolchain missing",
      };
    }

    /// Probe the Node version. The strip-types flag landed in
    /// 22.6.0 (unflagged in 24); below that we'd need a transpiler
    /// the extension doesn't ship, so we surface a clear "upgrade
    /// Node" message instead of a confusing parse error.
    const versionProbe = await spawnCapture(node, ["--version"], {
      timeoutMs: 3_000,
    });
    const versionStr = versionProbe.stdout.trim().replace(/^v/, "");
    const major = parseInt(versionStr.split(".")[0] ?? "0", 10);
    const minor = parseInt(versionStr.split(".")[1] ?? "0", 10);
    if (major < 22 || (major === 22 && minor < 6)) {
      return {
        status: "error",
        output: `Detected Node ${versionStr}. The TypeScript runner needs Node 22.6+ (for \`--experimental-strip-types\`). Upgrade via https://nodejs.org and reload the window.`,
        summary: "Node version too old",
      };
    }

    const scratch = path.join(input.scratchDir, "ts-scratch");
    await resetScratch(scratch);

    const userCode = (await readMaybe(input.userFilePath)) ?? "";
    /// Look for tests.ts first, then tests.js so this runner serves
    /// both javascript and typescript lessons.
    const tests =
      (await readMaybe(path.join(input.workspaceDir, ".libre", "tests.ts"))) ??
      (await readMaybe(path.join(input.workspaceDir, ".libre", "tests.js"))) ??
      "";
    /// We assemble solution + tests into ONE file rather than
    /// importing across files — that sidesteps Node's strict ESM
    /// resolution for `.ts` files (which still has rough edges in
    /// the experimental flag).
    const assembledPath = path.join(scratch, "run.ts");
    await fs.writeFile(
      assembledPath,
      TS_RUNTIME_HEADER + "\n" + userCode + "\n\n" + tests + "\n",
      "utf8",
    );

    const result = await spawnCapture(
      node,
      ["--experimental-strip-types", "--no-warnings", assembledPath],
      {
        cwd: scratch,
        timeoutMs: 30_000,
      },
    );

    const combined = trim(`${result.stdout}\n${result.stderr}`);
    if (result.timedOut) {
      return {
        status: "error",
        output:
          combined +
          "\n\nRunner timed out after 30s. The exercise might have an infinite loop — try again.",
        summary: "Timed out",
      };
    }
    const passed = result.exitCode === 0;
    return {
      status: passed ? "pass" : "fail",
      output: combined,
      exitCode: result.exitCode,
      summary: passed
        ? "All tests passed"
        : "Tests failed — see the Libre output panel",
    };
  },
};

function trim(s: string): string {
  return s.replace(/\s+$/u, "");
}
