//! Browser-OAuth for Apple + Google — the relay-mediated path.
//!
//! ## Flow
//!
//! ```text
//!  Desktop                  Browser                  API                Provider
//!     │                        │                       │                    │
//!     │ 1. open URL ──────────▶│                       │                    │
//!     │                        │ 2. GET /…/start ─────▶│                    │
//!     │                        │                       │ 3. 302 to ─────────▶
//!     │                        │                       │     provider auth  │
//!     │                        │ 4. user authenticates ─────────────────────│
//!     │                        │ 5. redirect ──────────│◀───────────────────│
//!     │                        │                       │     /…/callback?…  │
//!     │                        │                       │ 6. exchange code   │
//!     │                        │                       │     ──────────────▶│
//!     │                        │                       │ 7. ◀── id_token   │
//!     │                        │                       │ 8. mint Libre │
//!     │                        │                       │     token          │
//!     │                        │ 9. ◀── 302 ────────── │                    │
//!     │                        │     libre://oauth/done?…              │
//!     │ 10. deep-link ────────│                       │                    │
//!     │     captures token     │                       │                    │
//! ```
//!
//! The `state` parameter does double duty: a CSRF nonce that protects
//! the callback from replay, and a key into a server-side cache that
//! holds the `code_verifier` (PKCE) plus the desktop's `session` id
//! (so the deep-link callback knows which window to wake up — useful
//! when the user has multiple Libre instances open).
//!
//! The `session` id is generated by the desktop, passed through as a
//! query param on the start URL, round-tripped through the provider,
//! and echoed back to the desktop on the deep-link callback. The
//! desktop's `tauri-plugin-deep-link` handler matches on it.
//!
//! ## State cache
//!
//! In-memory `DashMap<state, OauthSessionEntry>` with a 10-minute
//! sweep. Restart wipes the cache, which is fine — the worst case is
//! a user who got distracted mid-auth has to click the button again.

use axum::{
    extract::{Form, Query, State},
    http::StatusCode,
    response::{IntoResponse, Redirect, Response},
};
use base64::Engine;
use dashmap::DashMap;
use jsonwebtoken::{EncodingKey, Header};
use once_cell::sync::Lazy;
use rand::RngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::sync::Arc;
use std::time::{Duration, Instant};

use super::oauth as token_verify;
use crate::auth::hash_token;
use crate::state::AppState;

const STATE_TTL: Duration = Duration::from_secs(10 * 60);

#[derive(Debug, Clone)]
struct OauthSessionEntry {
    /// Provider name — keeps the callback honest (a Google `code`
    /// posted to the Apple route gets rejected before we try to
    /// exchange).
    provider: Provider,
    /// PKCE verifier the desktop generated. We keep it server-side so
    /// the redirect URL can stay short and the user can't tamper with
    /// it via browser DevTools.
    code_verifier: String,
    /// Per-window id chosen by the desktop. Echoed back via the
    /// deep-link callback so multi-instance setups don't cross-wire.
    session: String,
    /// Display-name hint the desktop optionally passed in. Some
    /// flows (Apple) only return the user's name on first sign-in;
    /// the desktop UI lets the user fill it in if they want.
    display_name: Option<String>,
    /// Custom-scheme URL the desktop wants the browser to redirect
    /// back to once auth completes. Validated against an allow-list
    /// (must be `libre://` or `kata://`) on use.
    return_to: Option<String>,
    expires_at: Instant,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Provider {
    Apple,
    Google,
}

/// Process-global cache. `OnceCell::Lazy` rather than `AppState`
/// because we don't want to plumb a new field through everywhere — it
/// truly is a singleton, scoped to the API process lifetime.
static OAUTH_STATES: Lazy<DashMap<String, OauthSessionEntry>> =
    Lazy::new(DashMap::new);

fn random_url_safe(len_bytes: usize) -> String {
    let mut bytes = vec![0u8; len_bytes];
    rand::thread_rng().fill_bytes(&mut bytes);
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&bytes)
}

fn pkce_challenge(verifier: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(verifier.as_bytes());
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(hasher.finalize())
}

fn sweep() {
    let now = Instant::now();
    OAUTH_STATES.retain(|_, v| v.expires_at > now);
}

// ── Start endpoints ─────────────────────────────────────────────

#[derive(Deserialize)]
pub struct StartParams {
    /// Per-window id chosen by the desktop. Round-tripped through the
    /// provider and echoed back on the deep-link callback.
    pub session: String,
    /// Optional pre-filled display name (Apple sometimes returns the
    /// name only on first sign-in — desktop can let the user type it
    /// in advance).
    pub display_name: Option<String>,
    /// The custom URL scheme the desktop registered. Defaults to
    /// `libre://oauth/done` if omitted; tests can override it.
    pub return_to: Option<String>,
}

/// HTTPS return URLs we trust to receive a freshly-minted token.
/// The web build of Libre can't follow a `libre://` deep-link,
/// so its OAuth popup redirects through a same-origin `/oauth/done`
/// page that postMessages the token back to the parent. Any URL not
/// in this list (or matching the `libre://` / `kata://` scheme
/// allowlist below) falls through to the default `libre://oauth/done`,
/// which a browser can't follow — so an attacker who got the user
/// to click `return_to=https://attacker.com/log?token=` simply ends
/// up with a dead link in their popup, never the bearer.
///
/// Add new origins explicitly. Don't widen this to a wildcard.
const WEB_RETURN_ALLOWLIST: &[&str] = &[
    "https://libre.academy/oauth/done",
];

/// Build the deep-link return URL the desktop should be redirected
/// to once auth completes. Always passes through this single helper
/// so a redirect injection (`return_to=https://attacker.com`) gets
/// caught here — we only allow the configured scheme prefix or an
/// exact origin from `WEB_RETURN_ALLOWLIST`.
fn build_return_url(
    desired: Option<&str>,
    session: &str,
    payload: ReturnPayload,
) -> String {
    let base = desired.unwrap_or("libre://oauth/done");
    // Reject any return_to that isn't either:
    //   - a custom-scheme URL the desktop / iOS app handles, or
    //   - an exact-match entry from WEB_RETURN_ALLOWLIST (the
    //     libre.academy `/oauth/done` page that postMessages
    //     the token back to the popup opener).
    // The browser-OAuth handoff is the only sanctioned shape, and an
    // attacker who got the user to click a malicious link with
    // `return_to=https://attacker.com/log?libre_token=` would
    // otherwise leak the bearer.
    // `libre-dev://` is the desktop dev-build twin of `libre://`.
    // macOS Launch Services routes each custom scheme to whichever
    // `.app` bundle most recently registered it, and the installed
    // prod app re-claims `libre://` on every launch — meaning a
    // `tauri dev` session's OAuth callback gets hijacked by the prod
    // install. Splitting the scheme keeps dev callbacks landing in
    // the dev binary. The desktop config registers both schemes so
    // each build's Launch Services entry covers its own variant.
    let safe_base = if base.starts_with("libre://")
        || base.starts_with("libre-dev://")
        || base.starts_with("kata://")
        || WEB_RETURN_ALLOWLIST.iter().any(|allowed| base == *allowed)
    {
        base
    } else {
        "libre://oauth/done"
    };
    let mut url = url::Url::parse(safe_base).expect("valid scheme");
    {
        let mut q = url.query_pairs_mut();
        q.append_pair("session", session);
        match payload {
            ReturnPayload::Success { token } => {
                q.append_pair("status", "ok");
                q.append_pair("token", &token);
            }
            ReturnPayload::Error { code, message } => {
                q.append_pair("status", "error");
                q.append_pair("error", code);
                q.append_pair("message", message);
            }
        }
    }
    url.into()
}

enum ReturnPayload<'a> {
    Success { token: String },
    Error { code: &'a str, message: &'a str },
}

pub async fn google_start(
    State(state): State<Arc<AppState>>,
    Query(params): Query<StartParams>,
) -> Result<Redirect, StatusCode> {
    sweep();
    let client_id = state
        .google_audience
        .as_ref()
        .ok_or(StatusCode::SERVICE_UNAVAILABLE)?;
    let redirect_uri = state
        .public_url
        .as_ref()
        .map(|u| format!("{}/libre/auth/google/callback", u.trim_end_matches('/')))
        .ok_or(StatusCode::SERVICE_UNAVAILABLE)?;

    let csrf = random_url_safe(24);
    let verifier = random_url_safe(48);
    let challenge = pkce_challenge(&verifier);

    OAUTH_STATES.insert(
        csrf.clone(),
        OauthSessionEntry {
            provider: Provider::Google,
            code_verifier: verifier,
            session: params.session.clone(),
            display_name: params.display_name.clone(),
            return_to: params.return_to.clone(),
            expires_at: Instant::now() + STATE_TTL,
        },
    );

    let mut auth = url::Url::parse("https://accounts.google.com/o/oauth2/v2/auth")
        .expect("static URL");
    {
        let mut q = auth.query_pairs_mut();
        q.append_pair("client_id", client_id);
        q.append_pair("redirect_uri", &redirect_uri);
        q.append_pair("response_type", "code");
        q.append_pair("scope", "openid email profile");
        q.append_pair("state", &csrf);
        q.append_pair("code_challenge", &challenge);
        q.append_pair("code_challenge_method", "S256");
        // `prompt=select_account` lets users pick a fresh account
        // without first signing out of every Google session — common
        // request when sharing a machine.
        q.append_pair("prompt", "select_account");
    }
    Ok(Redirect::to(auth.as_str()))
}

pub async fn apple_start(
    State(state): State<Arc<AppState>>,
    Query(params): Query<StartParams>,
) -> Result<Redirect, StatusCode> {
    sweep();
    let client_id = state
        .apple_audience
        .as_ref()
        .ok_or(StatusCode::SERVICE_UNAVAILABLE)?;
    let redirect_uri = state
        .public_url
        .as_ref()
        .map(|u| format!("{}/libre/auth/apple/callback", u.trim_end_matches('/')))
        .ok_or(StatusCode::SERVICE_UNAVAILABLE)?;

    let csrf = random_url_safe(24);
    OAUTH_STATES.insert(
        csrf.clone(),
        OauthSessionEntry {
            provider: Provider::Apple,
            // Apple's web-flow doesn't use PKCE — leave verifier
            // empty; the lookup is by `state` key alone.
            code_verifier: String::new(),
            session: params.session.clone(),
            display_name: params.display_name.clone(),
            return_to: params.return_to.clone(),
            expires_at: Instant::now() + STATE_TTL,
        },
    );

    let mut auth = url::Url::parse("https://appleid.apple.com/auth/authorize")
        .expect("static URL");
    {
        let mut q = auth.query_pairs_mut();
        q.append_pair("client_id", client_id);
        q.append_pair("redirect_uri", &redirect_uri);
        q.append_pair("response_type", "code id_token");
        q.append_pair("scope", "name email");
        q.append_pair("state", &csrf);
        // form_post: Apple POSTs the result as form data instead of a
        // query string — required when the response includes
        // id_token.
        q.append_pair("response_mode", "form_post");
    }
    Ok(Redirect::to(auth.as_str()))
}

// ── Callback endpoints ──────────────────────────────────────────

#[derive(Deserialize)]
pub struct GoogleCallback {
    pub code: Option<String>,
    pub state: Option<String>,
    pub error: Option<String>,
}

pub async fn google_callback(
    State(state): State<Arc<AppState>>,
    Query(params): Query<GoogleCallback>,
) -> Response {
    sweep();
    let client_id = match &state.google_audience {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let client_secret = match &state.google_client_secret {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let public_url = match &state.public_url {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };

    let csrf = match params.state {
        Some(s) => s,
        None => return error_redirect(None, "missing_state", "Missing state param"),
    };
    let entry = match OAUTH_STATES.remove(&csrf) {
        Some((_, e)) => e,
        None => return error_redirect(None, "expired_state", "OAuth state expired or unknown"),
    };
    if entry.provider != Provider::Google {
        return error_redirect(
            Some(&entry),
            "wrong_provider",
            "State belongs to another provider",
        );
    }
    if let Some(err) = params.error {
        return error_redirect(Some(&entry), "provider_denied", &err);
    }
    let code = match params.code {
        Some(c) => c,
        None => return error_redirect(Some(&entry), "missing_code", "Missing auth code"),
    };

    let redirect_uri = format!(
        "{}/libre/auth/google/callback",
        public_url.trim_end_matches('/')
    );

    // Exchange the authorization code for tokens. Google accepts
    // either the client_secret OR PKCE — we send both, which is fine
    // (they're not mutually exclusive).
    let body = [
        ("client_id", client_id.as_str()),
        ("client_secret", client_secret.as_str()),
        ("code", code.as_str()),
        ("code_verifier", entry.code_verifier.as_str()),
        ("grant_type", "authorization_code"),
        ("redirect_uri", redirect_uri.as_str()),
    ];
    #[derive(Deserialize)]
    struct GoogleTokenRes {
        id_token: String,
    }
    let token_res: GoogleTokenRes = match reqwest::Client::new()
        .post("https://oauth2.googleapis.com/token")
        .form(&body)
        .send()
        .await
        .and_then(|r| r.error_for_status())
    {
        Ok(r) => match r.json().await {
            Ok(j) => j,
            Err(e) => {
                tracing::warn!("Google token JSON parse: {e}");
                return error_redirect(
                    Some(&entry),
                    "exchange_failed",
                    "Token exchange returned an unexpected payload",
                );
            }
        },
        Err(e) => {
            tracing::warn!("Google token exchange: {e}");
            return error_redirect(
                Some(&entry),
                "exchange_failed",
                "Couldn't exchange the auth code with Google",
            );
        }
    };

    let identity = match token_verify::verify_google(&token_res.id_token, client_id).await {
        Ok(i) => i,
        Err(e) => {
            tracing::warn!("Google id_token verify: {e}");
            return error_redirect(
                Some(&entry),
                "id_token_invalid",
                "Google id_token failed verification",
            );
        }
    };

    finalize_oauth(&state, &entry, identity).await
}

#[derive(Deserialize)]
pub struct AppleCallback {
    pub code: Option<String>,
    pub state: Option<String>,
    pub id_token: Option<String>,
    pub user: Option<String>,
    pub error: Option<String>,
}

/// Apple uses `response_mode=form_post`, so the callback arrives as
/// `application/x-www-form-urlencoded` body — Axum's `Form` extractor
/// handles that. We tolerate both POST (production) and GET (manual
/// dev testing where someone hand-builds the URL).
pub async fn apple_callback_post(
    State(state): State<Arc<AppState>>,
    Form(body): Form<AppleCallback>,
) -> Response {
    apple_callback_inner(state, body).await
}

pub async fn apple_callback_get(
    State(state): State<Arc<AppState>>,
    Query(body): Query<AppleCallback>,
) -> Response {
    apple_callback_inner(state, body).await
}

async fn apple_callback_inner(state: Arc<AppState>, body: AppleCallback) -> Response {
    sweep();
    let client_id = match &state.apple_audience {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let team_id = match &state.apple_team_id {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let key_id = match &state.apple_key_id {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let private_key_pem = match &state.apple_private_key_pem {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };
    let public_url = match &state.public_url {
        Some(s) => s,
        None => return service_unavailable_redirect(),
    };

    let csrf = match body.state {
        Some(s) => s,
        None => return error_redirect(None, "missing_state", "Missing state param"),
    };
    let entry = match OAUTH_STATES.remove(&csrf) {
        Some((_, e)) => e,
        None => return error_redirect(None, "expired_state", "OAuth state expired or unknown"),
    };
    if entry.provider != Provider::Apple {
        return error_redirect(
            Some(&entry),
            "wrong_provider",
            "State belongs to another provider",
        );
    }
    if let Some(err) = body.error {
        return error_redirect(Some(&entry), "provider_denied", &err);
    }

    // Apple sends the id_token directly in the form body when
    // response_type includes `id_token`, so we can sometimes skip the
    // code-exchange step. Accept either path.
    let id_token = if let Some(t) = body.id_token {
        t
    } else {
        let code = match body.code {
            Some(c) => c,
            None => {
                return error_redirect(Some(&entry), "missing_code", "Missing auth code")
            }
        };
        let client_secret = match make_apple_client_secret(
            team_id,
            client_id,
            key_id,
            private_key_pem,
        ) {
            Ok(s) => s,
            Err(e) => {
                tracing::error!("Apple client_secret JWT: {e}");
                return error_redirect(
                    Some(&entry),
                    "secret_jwt_failed",
                    "Couldn't construct the Apple client_secret JWT",
                );
            }
        };
        let redirect_uri = format!(
            "{}/libre/auth/apple/callback",
            public_url.trim_end_matches('/')
        );
        let form = [
            ("client_id", client_id.as_str()),
            ("client_secret", client_secret.as_str()),
            ("code", code.as_str()),
            ("grant_type", "authorization_code"),
            ("redirect_uri", redirect_uri.as_str()),
        ];
        #[derive(Deserialize)]
        struct AppleTokenRes {
            id_token: String,
        }
        match reqwest::Client::new()
            .post("https://appleid.apple.com/auth/token")
            .form(&form)
            .send()
            .await
            .and_then(|r| r.error_for_status())
        {
            Ok(r) => match r.json::<AppleTokenRes>().await {
                Ok(j) => j.id_token,
                Err(e) => {
                    tracing::warn!("Apple token JSON parse: {e}");
                    return error_redirect(
                        Some(&entry),
                        "exchange_failed",
                        "Apple token endpoint returned an unexpected payload",
                    );
                }
            },
            Err(e) => {
                tracing::warn!("Apple token exchange: {e}");
                return error_redirect(
                    Some(&entry),
                    "exchange_failed",
                    "Couldn't exchange the auth code with Apple",
                );
            }
        }
    };

    let mut identity = match token_verify::verify_apple(&id_token, client_id).await {
        Ok(i) => i,
        Err(e) => {
            tracing::warn!("Apple id_token verify: {e}");
            return error_redirect(
                Some(&entry),
                "id_token_invalid",
                "Apple id_token failed verification",
            );
        }
    };

    // Apple posts a `user` form field on the FIRST sign-in containing
    // `{"name": {"firstName": "...", "lastName": "..."}, "email": "..."}`.
    // After that it's never sent again — pull whatever's there now.
    if identity.name.is_none() {
        if let Some(user_json) = body.user.as_deref() {
            if let Ok(parsed) = serde_json::from_str::<serde_json::Value>(user_json) {
                let first = parsed
                    .pointer("/name/firstName")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let last = parsed
                    .pointer("/name/lastName")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let full = format!("{first} {last}").trim().to_string();
                if !full.is_empty() {
                    identity.name = Some(full);
                }
            }
        }
    }

    finalize_oauth(&state, &entry, identity).await
}

/// Build Apple's per-request `client_secret` — a 6-month JWT signed
/// with the developer's `.p8` key, ES256.
fn make_apple_client_secret(
    team_id: &str,
    client_id: &str,
    key_id: &str,
    private_key_pem: &str,
) -> anyhow::Result<String> {
    #[derive(Serialize)]
    struct AppleClaims<'a> {
        iss: &'a str,
        iat: u64,
        exp: u64,
        aud: &'a str,
        sub: &'a str,
    }
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)?
        .as_secs();
    let claims = AppleClaims {
        iss: team_id,
        iat: now,
        // Apple caps client_secret JWT lifetime at 6 months.
        exp: now + 60 * 60 * 24 * 30 * 5,
        aud: "https://appleid.apple.com",
        sub: client_id,
    };
    let mut header = Header::new(jsonwebtoken::Algorithm::ES256);
    header.kid = Some(key_id.to_string());
    let key = EncodingKey::from_ec_pem(private_key_pem.as_bytes())?;
    Ok(jsonwebtoken::encode(&header, &claims, &key)?)
}

async fn finalize_oauth(
    state: &AppState,
    entry: &OauthSessionEntry,
    identity: token_verify::OauthIdentity,
) -> Response {
    let display = entry.display_name.clone().or(identity.name.clone());
    let user_id_res = match entry.provider {
        Provider::Apple => state.db.find_or_create_apple_user(
            &identity.subject,
            identity.email.as_deref(),
            display.as_deref(),
        ),
        Provider::Google => state.db.find_or_create_google_user(
            &identity.subject,
            identity.email.as_deref(),
            display.as_deref(),
        ),
    };
    let user_id = match user_id_res {
        Ok(id) => id,
        Err(e) => {
            tracing::error!("upsert oauth user: {e}");
            return error_redirect(
                Some(entry),
                "db_error",
                "Couldn't save the account",
            );
        }
    };

    let token = mint_browser_oauth_token();
    let token_hash = match hash_token(&token) {
        Ok(h) => h,
        Err(e) => {
            tracing::error!("hash_token: {e}");
            return error_redirect(Some(entry), "db_error", "Couldn't issue a token");
        }
    };
    let token_id = uuid::Uuid::new_v4().to_string();
    let label = format!(
        "browser-oauth · {}",
        match entry.provider {
            Provider::Apple => "apple",
            Provider::Google => "google",
        }
    );
    if let Err(e) =
        state
            .db
            .store_token(&token_id, &user_id, &label, &token_hash)
    {
        tracing::error!("store_token: {e}");
        return error_redirect(Some(entry), "db_error", "Couldn't issue a token");
    }

    let url = build_return_url(
        entry.return_to.as_deref(),
        &entry.session,
        ReturnPayload::Success { token },
    );
    handoff_page(&url, true).into_response()
}

fn mint_browser_oauth_token() -> String {
    let bytes: [u8; 32] = rand::random();
    format!(
        "fb_{}",
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
    )
}

fn service_unavailable_redirect() -> Response {
    let url = build_return_url(
        None,
        "",
        ReturnPayload::Error {
            code: "not_configured",
            message: "Server-side OAuth credentials aren't configured",
        },
    );
    handoff_page(&url, false).into_response()
}

fn error_redirect(
    entry: Option<&OauthSessionEntry>,
    code: &str,
    message: &str,
) -> Response {
    let session = entry.map(|e| e.session.as_str()).unwrap_or("");
    let return_to = entry.and_then(|e| e.return_to.as_deref());
    let url =
        build_return_url(return_to, session, ReturnPayload::Error { code, message });
    handoff_page(&url, false).into_response()
}

/// Render a tiny HTML page that hands off to the desktop's custom URL
/// scheme, then tries to close the browser tab. Replaces the previous
/// raw 303-redirect response — that worked, but left the user staring
/// at a "Safari can't open this page" / blank page after the deep
/// link fired, which read as a broken flow even though the desktop
/// app had already received the token.
///
/// The page does three things on load:
///   1. Sets `window.location.href = <libre://...>`. This is what
///      actually fires the deep link (the `<meta refresh>` is a
///      redundant fallback for browsers that block JS).
///   2. Tries `window.close()` after a short delay. macOS Safari will
///      only honour close on windows it opened itself, but Chrome /
///      Firefox / Edge typically will once the deep-link has fired.
///   3. Shows a static fallback message so users on browsers that
///      can't auto-close get a clear "you can close this tab now".
///
/// Escaping: the `redirect_url` is built from already-allow-listed
/// custom-scheme URLs (`libre://` or `kata://`) plus query params
/// that come from server-controlled state, but we still HTML-escape it
/// before splicing in. Defense in depth — if a future change ever lets
/// a path land here that we don't fully control, the page won't become
/// an XSS vector.
fn handoff_page(redirect_url: &str, success: bool) -> Response {
    let escaped = html_escape(redirect_url);
    let title = if success {
        "Signed in — return to Libre"
    } else {
        "Sign-in failed — return to Libre"
    };
    let heading = if success { "Signed in!" } else { "Sign-in didn't complete" };
    let body_text = if success {
        "Return to the Libre app to keep going. You can close this tab."
    } else {
        "We couldn't finish the sign-in. Return to the Libre app and try again — you can close this tab."
    };

    // The HTML/CSS is intentionally inline + small. Caddy compresses
    // it with gzip, so the wire size is around 1 kB.
    let html = format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta http-equiv="refresh" content="0; url={escaped}">
  <style>
    :root {{
      color-scheme: light dark;
      font: 16px/1.5 -apple-system, "Segoe UI", system-ui, sans-serif;
    }}
    body {{
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      background: #fafafa;
      color: #1a1a1a;
    }}
    @media (prefers-color-scheme: dark) {{
      body {{ background: #111; color: #e8e8e8; }}
    }}
    .card {{
      max-width: 420px;
      padding: 32px;
      text-align: center;
    }}
    h1 {{ font-size: 22px; margin: 0 0 12px; }}
    p {{ margin: 0 0 16px; opacity: 0.8; }}
    button {{
      font: inherit;
      padding: 10px 18px;
      border-radius: 8px;
      border: 1px solid currentColor;
      background: transparent;
      color: inherit;
      cursor: pointer;
    }}
  </style>
</head>
<body>
  <div class="card">
    <h1>{heading}</h1>
    <p>{body_text}</p>
    <button type="button" onclick="window.close()">Close tab</button>
  </div>
  <script>
    // Fire the deep link. The browser hands off to whichever app
    // owns the `libre://` scheme (the installed Libre app).
    window.location.href = {js_url};
    // Attempt to close the tab a moment after. Most browsers will
    // honour this when the page was opened by another window/tab
    // (which is the case for OAuth pop-ups). Safari is stricter and
    // may leave the tab open — the explicit Close button covers that.
    setTimeout(function () {{ try {{ window.close(); }} catch (e) {{}} }}, 800);
  </script>
</body>
</html>
"##,
        title = title,
        escaped = escaped,
        heading = heading,
        body_text = body_text,
        js_url = json_string_literal(redirect_url),
    );

    (
        [(axum::http::header::CONTENT_TYPE, "text/html; charset=utf-8")],
        html,
    )
        .into_response()
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Render `s` as a JS string literal — surrounding quotes plus enough
/// escaping that arbitrary URL bytes splice in cleanly. Used inside
/// the inline `<script>` block where simple HTML-escape isn't enough
/// (a stray backslash or quote in the URL would terminate the string).
fn json_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '<' => out.push_str("\\u003c"), // prevent </script> embedding
            '>' => out.push_str("\\u003e"),
            '&' => out.push_str("\\u0026"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
