//! Libre Tauri backend.
//!
//! Exposes the narrow native API the frontend needs:
//!   - `run_swift` — writes user code to a temp file and execs the system
//!     `swift` toolchain against it. Fallback for a language we can't run
//!     in-browser.
//!   - `progress_db` — SQLite-backed lesson-completion store.
//!   - (future) `run_cargo_local`, `course_fs`.

mod ai_chat;
mod chains;
mod courses;
mod diagnostics;
mod docs_crawl;
mod epub_ingest;
mod http_proxy;
mod image_gen;
mod ingest;
mod ingest_cache;
// Ledger HID transport — desktop only. iOS / Android lack USB-HID
// access from app-sandboxed processes, and `hidapi-rs`'s build script
// hard-fails on those targets. Gating the module here AND the
// `hidapi` crate in Cargo.toml keeps the mobile builds clean.
#[cfg(not(any(target_os = "ios", target_os = "android")))]
mod ledger;
mod llm;
mod mobile_dev;
mod native_runners;
mod preview_server;
mod progress_db;
mod settings;
mod sveltekit_runner;
mod toolchain;
mod widget_snapshot;

use std::io::Write;
use std::process::Command;
use std::time::Instant;

use serde::Serialize;
use tauri::Manager;
use tauri_plugin_opener::OpenerExt;

#[derive(Debug, Serialize)]
pub struct SubprocessResult {
    pub stdout: String,
    pub stderr: String,
    pub success: bool,
    pub duration_ms: u64,
    /// Set when we couldn't even start the process (e.g. swift not installed).
    pub launch_error: Option<String>,
}

/// Runs the user's Swift source by writing it to a temp file and invoking the
/// system `swift` interpreter in script mode. Frontend parses stdout/stderr.
/// Returns `launch_error` rather than a Result-Err so the frontend can
/// distinguish "swift isn't installed" from a timeout or Rust-side panic.
#[tauri::command]
async fn run_swift(code: String) -> SubprocessResult {
    let start = Instant::now();

    let temp_path = std::env::temp_dir().join("libre-swift-run.swift");
    if let Err(e) = std::fs::File::create(&temp_path).and_then(|mut f| f.write_all(code.as_bytes())) {
        return SubprocessResult {
            stdout: String::new(),
            stderr: String::new(),
            success: false,
            duration_ms: start.elapsed().as_millis() as u64,
            launch_error: Some(format!("failed to write temp source: {e}")),
        };
    }

    let output = match Command::new("swift").arg(&temp_path).output() {
        Ok(o) => o,
        Err(e) => {
            let hint = if e.kind() == std::io::ErrorKind::NotFound {
                "swift toolchain not found on PATH — install Xcode Command Line Tools: `xcode-select --install`".to_string()
            } else {
                format!("failed to launch swift: {e}")
            };
            return SubprocessResult {
                stdout: String::new(),
                stderr: String::new(),
                success: false,
                duration_ms: start.elapsed().as_millis() as u64,
                launch_error: Some(hint),
            };
        }
    };

    SubprocessResult {
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        success: output.status.success(),
        duration_ms: start.elapsed().as_millis() as u64,
        launch_error: None,
    }
}

/// Open the relay's `/libre/auth/{provider}/start` URL in the
/// system browser. The relay redirects through the provider's OAuth
/// flow and finally back to `libre://oauth/done?...`, which the
/// deep-link plugin delivers to the frontend `onOpenUrl` listener.
///
/// The session id is generated by the frontend (random alphanumeric)
/// so we just need to forward it. We sanity-check it's
/// `[A-Za-z0-9_-]+` to avoid splicing attacker-controlled bytes into
/// the URL via a crafted invoke call from a compromised renderer.
///
/// KNOWN LIMITATION (dev mode, macOS): `tauri dev` on macOS produces
/// a bare binary with no `.app` bundle, which means it can't claim a
/// custom URL scheme via Launch Services. The OAuth callback to
/// `libre://oauth/done` ends up routed to the installed prod
/// `/Applications/Libre.app` instead. To sign in during a
/// `tauri dev` session today, use the email + password tab — that
/// path doesn't depend on the deep-link callback. A future iteration
/// will spin up a localhost HTTP listener for the OAuth callback,
/// which avoids the LS dance entirely; tracked for follow-up.
///
/// IMPORTANT: we route through `app.opener().open_url(...)` (the
/// `OpenerExt` instance method), NOT the bare
/// `tauri_plugin_opener::open_url()` free function. The free function
/// uses the cross-platform `open` crate, which on iOS shells out to
/// `xdg-open` / `open` — both forbidden by the iOS app sandbox, so the
/// call returns "Operation not permitted" and Sign-In-with-Apple dies
/// before reaching Safari. The instance method has separate
/// `#[cfg(desktop)]` / `#[cfg(mobile)]` impls; the mobile one runs the
/// plugin's Swift `open` handler which calls
/// `UIApplication.shared.open(url)` correctly.
#[tauri::command]
async fn start_oauth<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    provider: String,
    session_id: String,
) -> Result<(), String> {
    if provider != "apple" && provider != "google" {
        return Err(format!(
            "unsupported provider: {provider} (expected apple or google)"
        ));
    }
    if session_id.is_empty()
        || !session_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err("invalid session id (expected url-safe alphanumeric)".into());
    }
    let url = format!(
        "https://api.mattssoftware.com/libre/auth/{provider}/start?session={session_id}"
    );
    app.opener()
        .open_url(url, None::<&str>)
        .map_err(|e| format!("failed to open browser: {e}"))?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // rustls 0.23+ refuses to auto-pick a default crypto provider when
    // more than one (ring / aws-lc-rs) is linked into the binary —
    // callers have to call `install_default()` exactly once at
    // process start. Without this, the first reqwest HTTPS client
    // built inside our `tauri://` custom-protocol handler panics with
    // `No provider set` (originating from
    // `reqwest::async_impl::client::default_rustls_crypto_provider`),
    // which on iOS surfaces as the app launching to a blank screen
    // and hard-crashing the WKWebView process. Installing ring as the
    // default keeps behaviour identical to rustls's pre-0.23 default.
    // The error path (provider already installed) is benign — we
    // ignore the Result so a hot-reload that re-runs `run()` doesn't
    // double-install.
    let _ = rustls::crypto::ring::default_provider().install_default();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_dialog::init())
        // Updater: pulls a `latest.json` from the configured endpoint
        // (see `tauri.conf.json` plugins.updater) on demand and verifies
        // the bundle signature against the embedded public key. The
        // private key lives ONLY in the maintainer's keychain + the CI
        // secrets vault — losing it means rotating the public key and
        // shipping a manual-install version. Plugin is config-only on
        // the Rust side; all flow control happens from the JS via
        // `@tauri-apps/plugin-updater`.
        .plugin(tauri_plugin_updater::Builder::new().build())
        // Process: needed by the updater UI to call `relaunch()` after
        // the update is staged. Tiny plugin, no config required.
        .plugin(tauri_plugin_process::init())
        .setup(|app| {
            let db_path = progress_db::resolve_path(app.handle())?;
            let db = progress_db::open(db_path)?;
            app.manage(db);
            courses::ensure_seed(app.handle())?;

            // Load settings + expose as state so llm::structure_with_llm can
            // read the API key without the frontend passing it in every call.
            let initial = settings::read_from_disk(app.handle()).unwrap_or_default();
            app.manage(settings::SettingsState(parking_lot::Mutex::new(initial)));

            // SvelteKit runner state: holds Vite child-process handles
            // keyed by lesson id. Initially empty; populated when the
            // first SvelteKit lesson runs.
            app.manage(sveltekit_runner::SvelteKitRunners::default());

            // Ingest cancellation: one Notify shared across every in-flight
            // `call_llm`. The `cancel_ingest` command fires notify_waiters
            // which drops every in-flight reqwest future (tokio::select!
            // inside call_llm).
            app.manage(llm::IngestCancel::default());

            // Chain backends — see `chains.rs` for the architecture
            // overview. Each chain holds an `Arc<Mutex<...>>` registered
            // here so commands in `chains/<name>.rs` can `State<'_, ...>`
            // into them. Phases 5a-c wired SVM; Phase 5d.1 adds EVM;
            // Bitcoin lands in 5e.
            app.manage(std::sync::Arc::new(parking_lot::Mutex::new(
                chains::svm::SvmState::new(),
            )) as chains::svm::SharedSvm);
            app.manage(std::sync::Arc::new(parking_lot::Mutex::new(
                chains::evm::EvmState::new(),
            )) as chains::evm::SharedEvm);
            app.manage(std::sync::Arc::new(parking_lot::Mutex::new(
                chains::bitcoin::BitcoinState::new(),
            )) as chains::bitcoin::SharedBtc);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            run_swift,
            start_oauth,
            progress_db::list_completions,
            progress_db::mark_completion,
            progress_db::clear_completions,
            progress_db::clear_lesson_completion,
            progress_db::clear_course_completions,
            courses::list_courses,
            courses::list_courses_summary,
            courses::load_course,
            courses::save_course,
            courses::save_bundled_starter_course,
            courses::delete_course,
            courses::reset_seed_marker,
            courses::export_course,
            courses::import_course,
            courses::list_bundled_catalog_entries,
            diagnostics::run_diagnostics,
            courses::read_bundled_course,
            courses::download_and_install_course,
            courses::refresh_bundled_courses,
            ingest::extract_pdf_text,
            ingest::extract_pdf_cover,
            ingest::extract_source_text,
            ingest::extract_source_cover,
            ingest::import_course_cover,
            ingest::load_course_cover,
            ingest::load_course_covers,
            ingest::stat_file,
            ingest::extract_pdf_images,
            docs_crawl::crawl_docs_site,
            docs_crawl::extract_docs_nav,
            http_proxy::proxy_http,
            image_gen::generate_cover_art,
            toolchain::probe_language_toolchain,
            toolchain::install_language_toolchain,
            widget_snapshot::publish_widget_snapshot,
            settings::load_settings,
            settings::save_settings,
            llm::structure_with_llm,
            llm::clean_code,
            llm::outline_chapter,
            llm::generate_lesson,
            llm::generate_challenge,
            llm::generate_lesson_from_docs_page,
            llm::generate_chapter_capstone,
            llm::enrich_lesson,
            llm::detect_book_meta,
            llm::retry_exercise,
            llm::cancel_ingest,
            ingest_cache::cache_read,
            ingest_cache::cache_write,
            ingest_cache::cache_clear,
            preview_server::serve_web_preview,
            mobile_dev::open_in_ios_sim,
            mobile_dev::probe_expo_server,
            native_runners::run_c,
            native_runners::run_cpp,
            native_runners::run_java,
            native_runners::run_kotlin,
            native_runners::run_csharp,
            native_runners::run_asm,
            native_runners::run_ruby,
            native_runners::run_elixir,
            native_runners::run_haskell,
            native_runners::run_scala,
            native_runners::run_dart,
            native_runners::run_zig,
            ai_chat::ai_chat_probe,
            ai_chat::ai_chat_stream,
            ai_chat::ai_chat_install_status,
            ai_chat::ai_chat_install_ollama,
            sveltekit_runner::start_sveltekit,
            sveltekit_runner::stop_sveltekit,
            sveltekit_runner::current_sveltekit_url,
            ai_chat::ai_chat_start_ollama,
            ai_chat::ai_chat_pull_model,
            // Ledger HID transport — desktop-only (the module + the
            // hidapi crate are gated to non-iOS/Android targets in
            // Cargo.toml + lib.rs above). Mobile builds register
            // nothing under these names; the frontend never calls
            // them on mobile (LedgerStatusPill + DeviceAction render
            // disabled affordances when WebHID + ledger transport
            // are both unavailable).
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_list_devices,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_open,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_close,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_is_open,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_send_apdu,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_start_watcher,
            #[cfg(not(any(target_os = "ios", target_os = "android")))]
            ledger::ledger_stop_watcher,
            // Chain backends. Bitcoin lands in 5e.
            // SVM (Phases 5a + 5b + 5b+):
            chains::svm::svm_init,
            chains::svm::svm_get_snapshot,
            chains::svm::svm_reset,
            chains::svm::svm_balance,
            chains::svm::svm_airdrop,
            chains::svm::svm_transfer,
            chains::svm::svm_warp_slot,
            chains::svm::svm_warp_time,
            chains::svm::svm_send_tx,
            chains::svm::svm_deploy_program,
            chains::svm::svm_toolchain_status,
            chains::svm::svm_build_bpf,
            // EVM (Phases 5d.1 + 5d.2 + 5d.3):
            chains::evm::evm_init,
            chains::evm::evm_get_snapshot,
            chains::evm::evm_reset,
            chains::evm::evm_balance,
            chains::evm::evm_set_balance,
            chains::evm::evm_send_tx,
            chains::evm::evm_call,
            chains::evm::evm_get_code,
            chains::evm::evm_mine,
            chains::evm::evm_warp,
            chains::evm::evm_block_number,
            chains::evm::evm_block_timestamp,
            chains::evm::evm_snapshot,
            chains::evm::evm_revert,
            // Bitcoin (Phases 5e.1 + 5e.2 + 5e.3):
            chains::bitcoin::btc_init,
            chains::bitcoin::btc_get_snapshot,
            chains::bitcoin::btc_reset,
            chains::bitcoin::btc_balance,
            chains::bitcoin::btc_utxos,
            chains::bitcoin::btc_send,
            chains::bitcoin::btc_broadcast,
            chains::bitcoin::btc_mine,
            chains::bitcoin::btc_flush_mempool,
            chains::bitcoin::btc_snapshot,
            chains::bitcoin::btc_revert,
            chains::bitcoin::btc_get_tx,
            chains::bitcoin::btc_get_height,
            chains::bitcoin::btc_mempool,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
// rebuild at 1777311850
// rebuild with new pack at 1777312099
// pill nav at 1777312346
// outline at 1777312728
// settings + profile at 1777313447
// content change 1777318689
// covers injected 1777319119
// vyper cover 1777322019
// svelte cover 1777322193
// search palette 1777326175
// cloze + puzzle generator 1777337351
// deeplink + edge-scroll 1777338348
// icons + viewport-fit 1777340424
// next-button + state-leak fix 1777341320
// next + animations 1777341549
// micropuzzle 1777342507
// 147 drills + 792 cards 1777343961
// SEED_VERSION refresh path 1777350092
// practice tab + 2060 cards 1777355284
// practice hub/deck 1777357199
// profile gauges + heatmap 1777388151
// profile gauges 1777388223
// drill cleanup + quiz schema fix 1777389402
// tutorial cleanup + vyper drills 1777390480
// practice v2 + watch + difficulty 1777393300
// re-sync after tutorial-B difficulty 1777393391
