//! Fishbones Tauri backend.
//!
//! Exposes the narrow native API the frontend needs:
//!   - `run_swift` — writes user code to a temp file and execs the system
//!     `swift` toolchain against it. Fallback for a language we can't run
//!     in-browser.
//!   - `progress_db` — SQLite-backed lesson-completion store.
//!   - (future) `run_cargo_local`, `course_fs`.

mod ai_chat;
mod courses;
mod docs_crawl;
mod epub_ingest;
mod image_gen;
mod ingest;
mod ingest_cache;
mod llm;
mod mobile_dev;
mod native_runners;
mod preview_server;
mod progress_db;
mod settings;
mod sveltekit_runner;
mod toolchain;

use std::io::Write;
use std::process::Command;
use std::time::Instant;

use serde::Serialize;
use tauri::Manager;
use tauri_plugin_opener::OpenerExt;

#[derive(Debug, Serialize)]
pub struct SubprocessResult {
    pub stdout: String,
    pub stderr: String,
    pub success: bool,
    pub duration_ms: u64,
    /// Set when we couldn't even start the process (e.g. swift not installed).
    pub launch_error: Option<String>,
}

/// Runs the user's Swift source by writing it to a temp file and invoking the
/// system `swift` interpreter in script mode. Frontend parses stdout/stderr.
/// Returns `launch_error` rather than a Result-Err so the frontend can
/// distinguish "swift isn't installed" from a timeout or Rust-side panic.
#[tauri::command]
async fn run_swift(code: String) -> SubprocessResult {
    let start = Instant::now();

    let temp_path = std::env::temp_dir().join("fishbones-swift-run.swift");
    if let Err(e) = std::fs::File::create(&temp_path).and_then(|mut f| f.write_all(code.as_bytes())) {
        return SubprocessResult {
            stdout: String::new(),
            stderr: String::new(),
            success: false,
            duration_ms: start.elapsed().as_millis() as u64,
            launch_error: Some(format!("failed to write temp source: {e}")),
        };
    }

    let output = match Command::new("swift").arg(&temp_path).output() {
        Ok(o) => o,
        Err(e) => {
            let hint = if e.kind() == std::io::ErrorKind::NotFound {
                "swift toolchain not found on PATH — install Xcode Command Line Tools: `xcode-select --install`".to_string()
            } else {
                format!("failed to launch swift: {e}")
            };
            return SubprocessResult {
                stdout: String::new(),
                stderr: String::new(),
                success: false,
                duration_ms: start.elapsed().as_millis() as u64,
                launch_error: Some(hint),
            };
        }
    };

    SubprocessResult {
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        success: output.status.success(),
        duration_ms: start.elapsed().as_millis() as u64,
        launch_error: None,
    }
}

/// Open the relay's `/fishbones/auth/{provider}/start` URL in the
/// system browser. The relay redirects through the provider's OAuth
/// flow and finally back to `fishbones://oauth/done?...`, which the
/// deep-link plugin delivers to the frontend `onOpenUrl` listener.
///
/// The session id is generated by the frontend (random alphanumeric)
/// so we just need to forward it. We sanity-check it's
/// `[A-Za-z0-9_-]+` to avoid splicing attacker-controlled bytes into
/// the URL via a crafted invoke call from a compromised renderer.
///
/// IMPORTANT: we route through `app.opener().open_url(...)` (the
/// `OpenerExt` instance method), NOT the bare
/// `tauri_plugin_opener::open_url()` free function. The free function
/// uses the cross-platform `open` crate, which on iOS shells out to
/// `xdg-open` / `open` — both forbidden by the iOS app sandbox, so the
/// call returns "Operation not permitted" and Sign-In-with-Apple dies
/// before reaching Safari. The instance method has separate
/// `#[cfg(desktop)]` / `#[cfg(mobile)]` impls; the mobile one runs the
/// plugin's Swift `open` handler which calls
/// `UIApplication.shared.open(url)` correctly.
#[tauri::command]
async fn start_oauth<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    provider: String,
    session_id: String,
) -> Result<(), String> {
    if provider != "apple" && provider != "google" {
        return Err(format!(
            "unsupported provider: {provider} (expected apple or google)"
        ));
    }
    if session_id.is_empty()
        || !session_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err("invalid session id (expected url-safe alphanumeric)".into());
    }
    let url = format!(
        "https://api.mattssoftware.com/fishbones/auth/{provider}/start?session={session_id}"
    );
    app.opener()
        .open_url(url, None::<&str>)
        .map_err(|e| format!("failed to open browser: {e}"))?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let db_path = progress_db::resolve_path(app.handle())?;
            let db = progress_db::open(db_path)?;
            app.manage(db);
            courses::ensure_seed(app.handle())?;

            // Load settings + expose as state so llm::structure_with_llm can
            // read the API key without the frontend passing it in every call.
            let initial = settings::read_from_disk(app.handle()).unwrap_or_default();
            app.manage(settings::SettingsState(parking_lot::Mutex::new(initial)));

            // SvelteKit runner state: holds Vite child-process handles
            // keyed by lesson id. Initially empty; populated when the
            // first SvelteKit lesson runs.
            app.manage(sveltekit_runner::SvelteKitRunners::default());

            // Ingest cancellation: one Notify shared across every in-flight
            // `call_llm`. The `cancel_ingest` command fires notify_waiters
            // which drops every in-flight reqwest future (tokio::select!
            // inside call_llm).
            app.manage(llm::IngestCancel::default());
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            run_swift,
            start_oauth,
            progress_db::list_completions,
            progress_db::mark_completion,
            progress_db::clear_completions,
            progress_db::clear_lesson_completion,
            progress_db::clear_course_completions,
            courses::list_courses,
            courses::list_courses_summary,
            courses::load_course,
            courses::save_course,
            courses::delete_course,
            courses::export_course,
            courses::import_course,
            courses::refresh_bundled_courses,
            ingest::extract_pdf_text,
            ingest::extract_pdf_cover,
            ingest::extract_source_text,
            ingest::extract_source_cover,
            ingest::import_course_cover,
            ingest::load_course_cover,
            ingest::stat_file,
            ingest::extract_pdf_images,
            docs_crawl::crawl_docs_site,
            docs_crawl::extract_docs_nav,
            image_gen::generate_cover_art,
            toolchain::probe_language_toolchain,
            toolchain::install_language_toolchain,
            settings::load_settings,
            settings::save_settings,
            llm::structure_with_llm,
            llm::clean_code,
            llm::outline_chapter,
            llm::generate_lesson,
            llm::generate_challenge,
            llm::generate_lesson_from_docs_page,
            llm::generate_chapter_capstone,
            llm::enrich_lesson,
            llm::detect_book_meta,
            llm::retry_exercise,
            llm::cancel_ingest,
            ingest_cache::cache_read,
            ingest_cache::cache_write,
            ingest_cache::cache_clear,
            preview_server::serve_web_preview,
            mobile_dev::open_in_ios_sim,
            mobile_dev::probe_expo_server,
            native_runners::run_c,
            native_runners::run_cpp,
            native_runners::run_java,
            native_runners::run_kotlin,
            native_runners::run_csharp,
            native_runners::run_asm,
            ai_chat::ai_chat_probe,
            ai_chat::ai_chat_stream,
            ai_chat::ai_chat_install_status,
            ai_chat::ai_chat_install_ollama,
            sveltekit_runner::start_sveltekit,
            sveltekit_runner::stop_sveltekit,
            sveltekit_runner::current_sveltekit_url,
            ai_chat::ai_chat_start_ollama,
            ai_chat::ai_chat_pull_model,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
// rebuild at 1777311850
// rebuild with new pack at 1777312099
// pill nav at 1777312346
// outline at 1777312728
// settings + profile at 1777313447
// content change 1777318689
// covers injected 1777319119
// vyper cover 1777322019
// svelte cover 1777322193
// search palette 1777326175
// cloze + puzzle generator 1777337351
// deeplink + edge-scroll 1777338348
// icons + viewport-fit 1777340424
// next-button + state-leak fix 1777341320
// next + animations 1777341549
// micropuzzle 1777342507
// 147 drills + 792 cards 1777343961
// SEED_VERSION refresh path 1777350092
// practice tab + 2060 cards 1777355284
// practice hub/deck 1777357199
// profile gauges + heatmap 1777388151
// profile gauges 1777388223
// drill cleanup + quiz schema fix 1777389402
// tutorial cleanup + vyper drills 1777390480
// practice v2 + watch + difficulty 1777393300
// re-sync after tutorial-B difficulty 1777393391
