#!/usr/bin/env bash
# Self-hosted outbound SMTP for Libre.
#
# Installs Postfix + OpenDKIM on the VPS and configures them as a
# loopback-only submission server (the API binary connects to
# localhost:25 with no auth; nothing internet-facing). DKIM signing,
# queueing, and TLS to the recipient's mail server are Postfix's job.
#
# What the script does:
#   1. Installs postfix, opendkim, opendkim-tools.
#   2. Configures Postfix to listen on 127.0.0.1:25 and relay outbound
#      via direct MX delivery (no smarthost). Opportunistic TLS to
#      the receiving server.
#   3. Generates a 2048-bit DKIM key for the configured domain.
#   4. Wires OpenDKIM into Postfix as a milter so every outbound
#      message gets a DKIM-Signature header.
#   5. Writes the systemd-friendly drop-in for both services.
#   6. Prints the DNS records you must add at your registrar — SPF,
#      DKIM, DMARC. Without these, gmail.com / outlook.com etc.
#      will spam-folder or reject your mail.
#   7. Reminds you to set a reverse-DNS pointer at Vultr.
#
# Run this ONCE per VPS, after the API is already deployed. Re-running
# is safe — the script is idempotent (apt installs are no-ops, configs
# are overwritten with the same content, the DKIM key is preserved).
#
# Required env (read from ./.env if present; override on command line):
#   MAIL_DOMAIN=libre.academy   — the bare domain you send `From:`
#   MAIL_HOSTNAME=mail.libre.academy
#                                   — the FQDN announced by Postfix in
#                                     EHLO. Set Vultr's reverse DNS
#                                     for this VPS to this value too,
#                                     or receivers will reject the
#                                     PTR mismatch.
#   MAIL_DKIM_SELECTOR=mail         — the selector used in the DKIM
#                                     record's hostname; default `mail`.

set -euo pipefail

cd "$(dirname "$0")"

# Load .env so we can reuse VPS_* and friends from the API deploy.
if [ -f .env ]; then
  set -a; source .env; set +a
fi

if [ -z "${VPS_HOST:-}" ]; then
  echo "Error: VPS_HOST not set in .env"; exit 1
fi
if [ -z "${VPS_PASSWORD:-}" ]; then
  read -sp "Root password for $VPS_HOST: " VPS_PASSWORD
  echo
fi
if ! command -v sshpass &>/dev/null; then
  echo "Installing sshpass..."
  brew install sshpass 2>/dev/null || brew install esolitos/ipa/sshpass
fi

export SSHPASS="$VPS_PASSWORD"
SSH="sshpass -e ssh -o StrictHostKeyChecking=accept-new -p $VPS_PORT $VPS_USER@$VPS_HOST"

# Mail-specific config — sane defaults that the user can override.
MAIL_DOMAIN="${MAIL_DOMAIN:-libre.academy}"
MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.${MAIL_DOMAIN}}"
MAIL_DKIM_SELECTOR="${MAIL_DKIM_SELECTOR:-mail}"

echo "── Self-hosted mail setup for $MAIL_DOMAIN"
echo "    Hostname: $MAIL_HOSTNAME"
echo "    DKIM selector: $MAIL_DKIM_SELECTOR"
echo

# ── Install packages ────────────────────────────────────────────
# Postfix needs a non-interactive answer for its postinst questions
# ("internet site" / mail name) — debconf preseeding does that
# without the TUI prompt blocking the script.
echo "── Installing Postfix + OpenDKIM..."
$SSH "DEBIAN_FRONTEND=noninteractive bash -c '
  echo \"postfix postfix/main_mailer_type select Internet Site\" | debconf-set-selections
  echo \"postfix postfix/mailname string ${MAIL_HOSTNAME}\" | debconf-set-selections
  apt-get update -qq
  apt-get install -y -qq postfix opendkim opendkim-tools
'"

# ── Postfix main.cf ─────────────────────────────────────────────
# Listening only on loopback so nothing internet-facing is exposed —
# the API binary connects via 127.0.0.1:25 with no auth (trusted by
# `mynetworks=127.0.0.0/8`). Outbound goes direct to the recipient's
# MX with opportunistic STARTTLS.
echo "── Writing /etc/postfix/main.cf..."
$SSH "cat > /etc/postfix/main.cf <<'POSTFIX_CF'
# Generated by setup-mail.sh — re-run the script to update.

myhostname = ${MAIL_HOSTNAME}
mydomain = ${MAIL_DOMAIN}
myorigin = \$mydomain
mydestination = \$myhostname, localhost.\$mydomain, localhost
mynetworks = 127.0.0.0/8 [::1]/128
inet_interfaces = loopback-only
inet_protocols = all

# Opportunistic TLS to the receiving server. We don't enforce TLS on
# outbound because plenty of legitimate mail servers still don't
# support it, and the alternative is bouncing the message.
smtp_tls_security_level = may
smtp_tls_loglevel = 1

# DKIM signing happens inside OpenDKIM, wired in as a milter below.
milter_default_action = accept
milter_protocol = 6
smtpd_milters = inet:127.0.0.1:8891
non_smtpd_milters = inet:127.0.0.1:8891

# Standard sizing knobs — 25MB max message, two-day queue lifetime
# (Gmail starts deferring on its own after a day or two of bounces;
# anything older than 2d is going to the dead-letter queue regardless).
message_size_limit = 26214400
maximal_queue_lifetime = 2d
bounce_queue_lifetime = 2d

# Compatibility — Debian's postfix-loaded compatibility level. Setting
# it explicitly silences the boot warning on fresh installs.
compatibility_level = 3.6
POSTFIX_CF"

# ── OpenDKIM key + config ──────────────────────────────────────
echo "── Generating DKIM key (if missing)..."
$SSH "
  mkdir -p /etc/opendkim/keys/${MAIL_DOMAIN}
  cd /etc/opendkim/keys/${MAIL_DOMAIN}
  if [ ! -f ${MAIL_DKIM_SELECTOR}.private ]; then
    opendkim-genkey -b 2048 -d ${MAIL_DOMAIN} -s ${MAIL_DKIM_SELECTOR}
    chown opendkim:opendkim ${MAIL_DKIM_SELECTOR}.private
    chmod 600 ${MAIL_DKIM_SELECTOR}.private
    echo 'DKIM key generated.'
  else
    echo 'DKIM key already exists, leaving it alone.'
  fi
"

echo "── Writing /etc/opendkim.conf + /etc/default/opendkim..."
$SSH "cat > /etc/opendkim.conf <<'DKIM_CF'
# Generated by setup-mail.sh.
Syslog                  yes
UMask                   002
Domain                  ${MAIL_DOMAIN}
Selector                ${MAIL_DKIM_SELECTOR}
KeyFile                 /etc/opendkim/keys/${MAIL_DOMAIN}/${MAIL_DKIM_SELECTOR}.private
SignatureAlgorithm      rsa-sha256
Mode                    sv
Canonicalization        relaxed/relaxed
SubDomains              yes
AutoRestart             yes
AutoRestartRate         10/1h
Background              yes
DNSTimeout              5
SignatureTTL            0
Socket                  inet:8891@127.0.0.1
PidFile                 /run/opendkim/opendkim.pid
UserID                  opendkim
DKIM_CF

# Make sure the runtime dir exists and is owned by the opendkim user.
mkdir -p /run/opendkim
chown opendkim:opendkim /run/opendkim

cat > /etc/default/opendkim <<'DKIM_DEFAULTS'
# Generated by setup-mail.sh.
RUNDIR=/run/opendkim
SOCKET=inet:8891@127.0.0.1
USER=opendkim
GROUP=opendkim
PIDFILE=\$RUNDIR/\$NAME.pid
EXTRAAFTER=
DKIM_DEFAULTS

systemctl enable opendkim postfix
systemctl restart opendkim
systemctl restart postfix
"

# ── Sanity checks ──────────────────────────────────────────────
echo "── Verifying services are up..."
$SSH "systemctl is-active opendkim && systemctl is-active postfix" || {
  echo "Error: postfix or opendkim failed to start. Check 'journalctl -u postfix -u opendkim'."
  exit 1
}

# ── DNS records ────────────────────────────────────────────────
# Pull the public DKIM key off the VPS so we can print the exact TXT
# record the user needs to add. The .txt file opendkim-genkey emits
# wraps the key with parentheses + quotes — strip those for clarity.
echo
echo "── DNS records to add at your registrar for ${MAIL_DOMAIN} ──"
echo

echo "1. SPF (TXT record on the bare domain or the configured subdomain):"
echo "   Host:  @  (or the bare ${MAIL_DOMAIN})"
echo "   Type:  TXT"
echo "   Value: \"v=spf1 ip4:${VPS_HOST} -all\""
echo
echo "   If you already have an SPF record (e.g. for Resend or"
echo "   another sender), MERGE this one — only one SPF record per host."
echo "   Combined example: \"v=spf1 ip4:${VPS_HOST} include:_spf.google.com -all\""
echo

echo "2. DKIM (TXT record at ${MAIL_DKIM_SELECTOR}._domainkey.${MAIL_DOMAIN}):"
echo "   Host:  ${MAIL_DKIM_SELECTOR}._domainkey"
echo "   Type:  TXT"
echo "   Value:"
$SSH "cat /etc/opendkim/keys/${MAIL_DOMAIN}/${MAIL_DKIM_SELECTOR}.txt" \
  | sed -E 's/^.*"v=DKIM1[^"]*".*$/\0/' \
  | tr -d '\n' \
  | sed -E 's/.*\(\s*//; s/\s*\)\s*;\s*$//' \
  | sed -E 's/"\s+"//g' \
  | sed -E 's/^/          /'
echo
echo
echo "   (Many DNS providers limit TXT values to 255 chars — use the"
echo "   provider's 'long TXT' or 'auto-split' affordance if so.)"
echo

echo "3. DMARC (TXT record at _dmarc.${MAIL_DOMAIN}):"
echo "   Host:  _dmarc"
echo "   Type:  TXT"
echo "   Value: \"v=DMARC1; p=none; rua=mailto:postmaster@${MAIL_DOMAIN}; ruf=mailto:postmaster@${MAIL_DOMAIN}; fo=1\""
echo
echo "   Start with p=none so failing mail isn't dropped while the"
echo "   setup is being verified. Once you've watched a few days of"
echo "   reports and confirmed everything's signing correctly, tighten"
echo "   to p=quarantine or p=reject."
echo

echo "── Reverse DNS (PTR) ──"
echo
echo "Outbound mail to gmail.com / outlook.com is rejected without a"
echo "matching PTR. Set the reverse-DNS pointer for ${VPS_HOST} to"
echo "${MAIL_HOSTNAME} at Vultr:"
echo "   1. Vultr dashboard → your VPS → Settings → IPv4."
echo "   2. Click the pencil next to the IP, set 'Reverse DNS' to"
echo "      ${MAIL_HOSTNAME}, save."
echo "   3. Verify with: dig -x ${VPS_HOST} +short"
echo "      (should print '${MAIL_HOSTNAME}.')"
echo

echo "── Wire the API to use SMTP ──"
echo
echo "Edit api/.env on your laptop and add:"
echo
echo "   SMTP_HOST=localhost"
echo "   SMTP_PORT=25"
echo "   SMTP_STARTTLS=false"
echo "   SMTP_FROM=noreply@${MAIL_DOMAIN}"
echo "   SMTP_FROM_NAME=Libre"
echo
echo "Then re-run ./deploy.sh — the API will start sending via Postfix"
echo "instead of falling back to the tracing log."
echo
echo "── Test the loop ──"
echo
echo "After DNS has propagated (give it 5–15 minutes), trigger a"
echo "password reset against an email you control and check inbox + spam:"
echo
echo "   curl -s -X POST -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"YOUR_REAL_EMAIL\"}' \\"
echo "     https://api.libre.academy/auth/password-reset/request"
echo
echo "If the message lands in spam, run it through https://www.mail-tester.com"
echo "and follow whichever score-reducer it points at."
echo
echo "── setup-mail.sh complete."
